blank_issues_enabled: false
contact_links:
  - name: Report a security issue
    url: https://github.com/stephenjude/filament-blog/security/policy
    about: Learn how to notify us for sensitive bugs
